### ISSUE TITLE
Problem executing Robot-One with MatLab in Ubuntu 18.04

### ISSUE THREAD

**Issue by mateusnazarioc** [AlexanderSilvaB/Robot-One#1]
I'm having some trouble to execute Robot-One with MatLab in Ubuntu 18.04 when trying to connect.
Photo of the problem in MatLab's terminal attached.
_______
No mais, parabéns pelo simulador, Alexander :) 
Estamos utilizando ele na disciplina de Robótica Móvel na Ufop.

Abraços!
![matlab_robotone](https://user-images.githubusercontent.com/44046504/65934394-9188eb80-e3eb-11e9-8a7a-dafbe4dccb45.png)

**Comment by AlexanderSilvaB** [comment]
Oi Mateus! Rapaz, mil desculpas pela demora pra responder, eu não tinha visto a notificação. Vou ver aqui o que pode ser, tentar corrigir e te dou uma resposta. 
Muito obrigado pelo feedback e pelo elogio, que ótimo que está sendo útil.
Abraços! Assim que eu conseguir resolver aqui, te aviso.

**Comment by mateusnazarioc** [comment]
Que isso, mestre. Tamo junto demais ahahahaha fico no aguardo. Obrigado pelo feedback! :)

**Comment by AlexanderSilvaB** [comment]
Rapaz, tudo joia? 
Atualizei o ultimo release pra linux com uma correção. Testei em um pc com o Ubuntu 18.04 recém instalado e funcionou tudo como esperado. A versão antiga estava com um erro de digitação no script pra linux, daí a lib do R-one estava compilando com a versão errada do gcc.
Depois que testar ai me dê um feedback pra ver se preciso alterar algo mais. 
Muito obrigado!

**Comment by mateusnazarioc** [comment]
Fala, mestre!
Cara, fui executar aqui mas não encontrei o installer pra linux dentro do source...tô dando bobeira em alguma etapa aqui? hahahaha
Obrigado pela atenção, mesmo.
Abração!

**Comment by mateusnazarioc** [comment]
Vi que o /installLinux.sh tá no softwares, joguei ele pro src mas a etapa final da instalação ele n consegue criar o executável...
Consegue me ajudar no tutorial aí? ahahahah da outra vez eu consegui mas n lembro o que fiz de diferente...

**Comment by AlexanderSilvaB** [comment]
Então cara, não precisa baixar o código não, ele está organizado pro compilador, pra instalar usando ele vc teria que rodar os scripts de preparar algum release. A melhor forma é você baixar o release diretamente: [Latest Release Linux](https://github.com/AlexanderSilvaB/Robot-One/releases/download/v0.1.3-beta/robotOne-linux-x86_64.zip)

Com esse arquivo baixado, é só você extrair, acessar a pasta extraida, dar permissão de execução pro script install.sh (chmod +x install.sh), e depois executá-lo (./install.sh). Fazendo isso, o script vai instalar os requerimentos (g++4.9), instalar o executável do simulador, compilar a lib de comunicação e instalar os exemplos.

Qualquer coisa é só avisar aqui :)

**Comment by AlexanderSilvaB** [comment]
Depois de instalar, tudo vai estar instalado em uma pasta chamada "robot-one" no seu diretório pessoal, ai pra usar pelo matlab é só adicioanar o path da lib no seu matlab (/home/yourUserName/robot-one/lib/matlab/robotOne). Infelizmente ainda não consegui uma forma de adicionar isso ao matlab automaticamente.

**Comment by mateusnazarioc** [comment]
![image](https://user-images.githubusercontent.com/44046504/68444328-5087b200-01b5-11ea-8538-de69101149db.png)

Cara, a instalação rodou perfeita, eu esqueci que tinha que puxar do release do linux e n do master...bobeira mesmo.
Tá aparecendo isso depois de localizar o path (ou nesse caso, aonde criei o próprio script de teste dentro da lib mesmo).

**Comment by AlexanderSilvaB** [comment]
Uhm, provavelmente deu algum problema na hora de compilar as libs, geralmente é por alguma dependência. 

Testa duas coisas pra mim se não for incômodo?
Verificar se a lib foi compilada: "ls /usr/local/lib/ | grep robotOne"
Verificar se o gcc 4.9 foi instalado: "gcc-4.9 -v"

**Comment by mateusnazarioc** [comment]
![image](https://user-images.githubusercontent.com/44046504/68445104-b412df00-01b7-11ea-95e8-f7cc63931305.png)
ta aí hehe

**Comment by AlexanderSilvaB** [comment]
Em teoria está tudo correto, mas por algum motivo o matlab ainda não está conseguindo encontrar a librobotOne.so. 
Rapaz, de dentro dessa pasta de arquivos do matlab, roda esse comando fazendo favor: 
"loadlibrary('/usr/local/lib/librobotOne.so', 'robotOne.h', 'alias', 'librobotOne')"
Isso vai forçar o matlab usar o caminho absoluto do arquivo. Vamos ver se assim ele encontra a lib.
Obrigado! E desculpa o incômodo :)

**Comment by mateusnazarioc** [comment]
Rolou, cara! :) me desculpa eu pelo incômodo hahaha vou passar as orientações pro pessoal quanto ao simulador. Valeu demais.

**Comment by AlexanderSilvaB** [comment]
Ah, que ótimo que agora deu certo. Vou colocar esse último passo como automático na lib. Muito obrigado!
